---
- name: build tools installed
  apt: name={{ item }}
  loop: [make, libelf-dev, linux-headers-generic, build-essential]

- name: lkrg repo cloned
  git:
    repo: "{{ lkrg_repo }}"
    dest: "{{ lkrg_build_dir }}"
    version: HEAD
  register: git

- name: lkrg built # noqa 503
  make:
    chdir: "{{ lkrg_build_dir }}"
    target: "{{ item }}"
  loop: [clean,all]
  when: git.changed
  register: build

- name: lkrg installed # noqa 503
  make:
    chdir: "{{ lkrg_build_dir }}"
    target: "{{ item }}"
  # install script errors when service is already there thus uninstall
  loop: [uninstall,install]
  when: build.changed

- name: lkrg service set up
  service:
    name: lkrg
    state: started
    enabled: yes
